### ISSUE TITLE
this.$refs.myRef.start(), start回调未支持吗

### ISSUE THREAD

**Issue by sigmadfzb** [xiaofan9/vue-count-to#2]
**Uncaught (in promise) TypeError: this.$refs.myRef.start is not a function**

这是start回调未支持吗？

**Comment by xiaofan9** [comment]
> **Uncaught (in promise) TypeError: this.$refs.myRef.start is not a function**
> 
> 这是start回调未支持吗？

暂未支持这块，有计划在这几天内升级（ps: 年前实在太忙了），到时候将支持代码智能提示，vue-count methods 对应方法的支持等等

**Comment by xiaofan9** [comment]
最新的v1.0.8版本，已经进行start，pause，reset方法的支持，以及实现了vs code代码智能提示
