### ISSUE TITLE
为什么我使用你写的vue3-count-to没有生效

### ISSUE THREAD

**Issue by guoguoqd** [xiaofan9/vue-count-to#3]
使用的是vue3-count-to，但是在引入的时候，确报没有这个模块。正常引入import CountTo from 'vue3-count-to';  打印console.log(CountTo) 发现这个值是一个object，里面的值是{version:"1.0.8",install:f}这是什么原因造成的 @xiaofan9 麻烦帮忙解决一下，谢谢

**Comment by xiaofan9** [comment]
局部使用时，请这样使用：
```javascript
import { CountTo } from 'vue3-count-to';

export default {
  components: { CountTo }
}
```

这个一般搭配着Vue.use
```javascript
import CountTo from 'vue3-count-to';
import Vue from 'vue'; // vue2

Vue.use(CountTo);
```

**Comment by guoguoqd** [comment]
按照您的方式现在dom 树是已经挂载了，但是为啥页面没有展示出这个功能








------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月8日(星期四) 上午10:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xiaofan9/vue-count-to] 为什么我使用你写的vue3-count-to没有生效 (#3)





 
局部使用时，请这样使用：
 import { CountTo } from 'vue3-count-to'; export default {   components: { CountTo } }
 
这个一般搭配着Vue.use
 import CountTo from 'vue3-count-to'; import Vue from 'vue'; // vue2 Vue.use(CountTo);

**Comment by guoguoqd** [comment]
按照您的方式现在dom 树是已经挂载了，但是为啥页面没有展示出这个功能，而且给他定义长宽了，但是还是0，麻烦帮忙看一下，谢谢

**Comment by xiaofan9** [comment]
> 按照您的方式现在dom 树是已经挂载了，但是为啥页面没有展示出这个功能，而且给他定义长宽了，但是还是0，麻烦帮忙看一下，谢谢

能给出个在线示例么？像这种的[codepen](https://codepen.io/xiaofan9/pen/QWGGdKJ)

**Comment by guoguoqd** [comment]
是不是还有css没有加载进来？
整个组件操作代码如下：






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月8日(星期四) 中午11:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xiaofan9/vue-count-to] 为什么我使用你写的vue3-count-to没有生效 (#3)





  
按照您的方式现在dom 树是已经挂载了，但是为啥页面没有展示出这个功能，而且给他定义长宽了，但是还是0，麻烦帮忙看一下，谢谢
  
能给出个在线示例么？像这种的codepen

**Comment by xiaofan9** [comment]
你没有提供示例给我。

不需要额外加载css

**Comment by guoguoqd** [comment]
我给你截得图片就是我写的实例，你可以看一下我给你的截图



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月8日(周四) 中午12:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaofan9/vue-count-to] 为什么我使用你写的vue3-count-to没有生效 (#3)




 
你没有提供示例给我。
 
不需要额外加载css

**Comment by xiaofan9** [comment]
没看到任何图片

**Comment by guoguoqd** [comment]
这就奇怪了，我明明发了图片的，还有标记，现在我直接把代码敲上吧：就是如下代码
<template>
     <count-to :startVal="startVal" :endVal="endVal" :duration='3000'></count-to>
</template>
<script>
import { CountTo } from 'vue3-count-to';
export default {
    components: {CountTo},
     data () {
        return{
            startVal: 0,
            endVal: 2017
        }
    },
}
</script>
<style scoped>
.text-style{
    width: 100px;
    height: 100px;
}

</style>

**Comment by guoguoqd** [comment]
如果您方便的话发一个邮箱给我，我直接发你邮箱

**Comment by xiaofan9** [comment]
> 如果您方便的话发一个邮箱给我，我直接发你邮箱

718662552@qq.com

**Comment by p1Master** [comment]
Component is missing template or render function @xiaofan9

**Comment by guoguoqd** [comment]
这是什么原因造成的？
我引入的其他组件又可以，唯独这个不行




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月8日(星期四) 下午3:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xiaofan9/vue-count-to] 为什么我使用你写的vue3-count-to没有生效 (#3)





 
Component is missing template or render function @xiaofan9

**Comment by guoguoqd** [comment]
安装方式也是按照你给的文档来的，为啥会报这种问题？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaofan9/vue-count-to"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月8日(星期四) 下午3:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaofan9/vue-count-to] 为什么我使用你写的vue3-count-to没有生效 (#3)





 
Component is missing template or render function @xiaofan9

**Comment by xiaofan9** [comment]
我看了下，是判断vue2, vue3区分的逻辑出错了，错误的把vue2认知成了vue3，现在在紧急修复中

**Comment by guoguoqd** [comment]
好的，好了通知一声，我现在用的是vue3




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月8日(星期四) 下午3:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xiaofan9/vue-count-to] 为什么我使用你写的vue3-count-to没有生效 (#3)





 
我看了下，是判断vue2, vue3区分的逻辑出错了，错误的把vue2认知成了vue3，现在在紧急修复中

**Comment by xiaofan9** [comment]
> Component is missing template or render function @xiaofan9

vue2?

**Comment by guoguoqd** [comment]
vue3，现在刚开使用vue3做项目




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaofan9/vue-count-to"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月8日(星期四) 下午4:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaofan9/vue-count-to] 为什么我使用你写的vue3-count-to没有生效 (#3)





  
Component is missing template or render function @xiaofan9
  
vue2?

**Comment by p1Master** [comment]
> > Component is missing template or render function @xiaofan9
> 
> vue2?

Vue3

**Comment by xiaofan9** [comment]
> vue3，现在刚开使用vue3做项目
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xiaofan9/vue-count-to" ***@***.***&gt;; 发送时间:&nbsp;2021年4月8日(星期四) 下午4:17 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [xiaofan9/vue-count-to] 为什么我使用你写的vue3-count-to没有生效 (#3) Component is missing template or render function @xiaofan9 vue2? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我没法复现你的问题

**Comment by xiaofan9** [comment]
> > > Component is missing template or render function @xiaofan9
> > 
> > 
> > vue2?
> 
> Vue3

这么奇怪？能提供个在线示例么？因为我在测试时多是能够正常使用的

**Comment by guoguoqd** [comment]
是挺奇怪的，我刚跑了一下你给我的那个包，是可以的，我分析了一下刚开始以为是我的用的不是ts开发的，所以会出现这种情况，但是修改成和你一样的时候，还是不行，




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月8日(星期四) 下午5:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xiaofan9/vue-count-to] 为什么我使用你写的vue3-count-to没有生效 (#3)





    
Component is missing template or render function @xiaofan9
  
vue2?
  
Vue3
  
这么奇怪？能提供个在线示例么？因为我在测试时多是能够正常使用的

**Comment by xiaofan9** [comment]
是vite1.0 bug, 目前官方已经弃用了vite，建议使用2.0.如果非要使用1.0，可以使用beta版
```javascript
yarn add vue3-count-to@beta -S
# 或
npm install vue3-count-to@beta -S
```
