### ISSUE TITLE
Vue3 + ts 使用这个组件报警告

### ISSUE THREAD

**Issue by xiaojieajie** [xiaofan9/vue-count-to#5]
类型 "{ ref: string; startVal: number; 'start-val': number; endVal: number; 'end-val': number; duration: number; class: string; }" 中缺少属性 "prototype"，但类型 "typeof CountTo" 中需要该属性。ts(2345)

**Comment by xiaofan9** [comment]
麻烦提供下复现方式，我这边并没有出现类似问题

**Comment by xiaojieajie** [comment]
![微信截图_20210729190158](https://user-images.githubusercontent.com/39750199/127481169-846af49f-62ba-437a-a14f-842fde8e0046.png)

**Comment by xiaojieajie** [comment]
版本号是"^1.0.9",

**Comment by xiaojieajie** [comment]
我是用vite2搭建的工程，不知道是不是这个原因

**Comment by xiaofan9** [comment]
![image](https://user-images.githubusercontent.com/16103130/127612731-4951c1ea-51a8-4824-bbbf-c179057799e2.png)
vite2 + 1.0.9 依旧没复现。你要不把项目去除核心上传上来看下呗 @xiaojieajie

**Comment by jinxinkai** [comment]
JSX element class does not support attributes because it does not have a '$props' property.

**Comment by xiaojieajie** [comment]
你有没有装vscode的，volar插件，如果你没装的话，你build一下项目试试，应该会提示CountTo报错不给打包

项目的话就是这个https://github.com/RainManGO/vue3-composition-admin

**Comment by xiaofan9** [comment]
> 你有没有装vscode的，volar插件，如果你没装的话，你build一下项目试试，应该会提示CountTo报错不给打包
> 
> 项目的话就是这个https://github.com/RainManGO/vue3-composition-admin

额，这打包成功了。
![image](https://user-images.githubusercontent.com/16103130/127818188-a5f85c37-10be-4102-ac92-157e12e48717.png)
然后也能跑起来
![image](https://user-images.githubusercontent.com/16103130/127818250-3a6402a6-f186-411e-8dde-cbaa3f88bca7.png)

**Comment by xiaojieajie** [comment]
那你装了volar之后，在这个项目进入，views/dashboard/admin/components/PanelGroup.vue，移动到那个CountTo，组件会提示我这个吗。这个应该会了吧

**Comment by xiaofan9** [comment]
> 那你装了volar之后，在这个项目进入，views/dashboard/admin/components/PanelGroup.vue，移动到那个CountTo，组件会提示我这个吗。这个应该会了吧

我尝试下

**Comment by jinxinkai** [comment]
> 那你装了volar之后，在这个项目进入，views/dashboard/admin/components/PanelGroup.vue，移动到那个CountTo，组件会提示我这个吗。这个应该会了吧

declare const CountTo: any
暂时解决

**Comment by xiaojieajie** [comment]
> > 那你装了volar之后，在这个项目进入，views/dashboard/admin/components/PanelGroup.vue，移动到那个CountTo，组件会提示我这个吗。这个应该会了吧
> 
> declare const CountTo: any
> 暂时解决

这句声明加在哪里呢

**Comment by jinxinkai** [comment]
> > > 那你装了volar之后，在这个项目进入，views/dashboard/admin/components/PanelGroup.vue，移动到那个CountTo，组件会提示我这个吗。这个应该会了吧
> > 
> > 
> > declare const CountTo: any
> > 暂时解决
> 
> 这句声明加在哪里呢

全局声明文件即可

**Comment by xiaojieajie** [comment]
> > > > 那你装了volar之后，在这个项目进入，views/dashboard/admin/components/PanelGroup.vue，移动到那个CountTo，组件会提示我这个吗。这个应该会了吧
> > > 
> > > 
> > > declare const CountTo: any
> > > 暂时解决
> > 
> > 
> > 这句声明加在哪里呢
> 
> 全局声明文件即可

好的，我明天试试，谢谢

**Comment by xiaofan9** [comment]
> > 那你装了volar之后，在这个项目进入，views/dashboard/admin/components/PanelGroup.vue，移动到那个CountTo，组件会提示我这个吗。这个应该会了吧
> 
> declare const CountTo: any
> 暂时解决

明白了，我大概知道什么问题了，我这边这几天找个时间处理下

**Comment by xiaofan9** [comment]
已经修复，并发布了v1.1.0版本（该版本起，仅支持vue3）

**Comment by xiaojieajie** [comment]
> 已经修复，并发布了v1.1.0版本（该版本起，仅支持vue3）

辛苦了，作者
