### ISSUE TITLE
using lodash-es as a dependency

### ISSUE THREAD

**Issue by flipvh** [xiaofan9/vue-count-to#6]
Hi there, 

While analyzing our JS filesize I saw this app is importing the whole lodash-es library. Is it perhaps possible to load only the lodash function which you need? I think only cloneDeep is used. 

Please let me know if you want me to make a pull request. Thanks!

**Comment by xiaofan9** [comment]
ok，I will try to remove lodash-es.If you want to solve this problem quickly, you can provide a merge pull request

**Comment by xiaofan9** [comment]
The latest package has been released, removing the reference to lodash

**Comment by xiaofan9** [comment]
The latest package has been released, removing the reference to lodash
